export * from './common';
export * from './academic';
export * from './interactive';
export * from './visual';
export * from './practical';
export * from './modern';
export * from './edu-dark';
export * from './vocational';
export { LAYOUT_ID_ALIASES, normalizeLayoutId, resolveThemeLayout } from './aliases';
export { layoutNames, getLayoutDisplayName } from './names';
export { renderLayoutHTML } from './registry';
